# configs/baseline_transformer.yaml
# Baseline Transformer (T5) 모델 설정

model_params:
  model_name: "t5-small"

train_params:
  batch_size: 8
  eval_batch_size: 16
  learning_rate: 3e-5
  weight_decay: 1e-5

